### ISSUE TITLE
博客不支持RSS订阅

### ISSUE THREAD

**Issue by EscapeLife** [baoshishu/blog-site#1]
1. 对于使用feedly的用户来说，就是噩梦！
2. 不知道是否可以支持下呢？
3. 祝身体健康，腰好，肩膀好！

**Comment by ryanwang520** [comment]
已加

**Comment by EscapeLife** [comment]
@ryanwang520 RSS订阅有问题，域名和地址之前没有/符号，你可以试试看

- `https://blog.baoshishu.comcommon-pitfalls-for-database-schema-design/`

**Comment by ryanwang520** [comment]
已修复 谢谢
